# Generated by Django 5.0 on 2026-01-11 15:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_transcript', models.TextField(help_text='Complete transcript of all recordings')),
                ('word_count', models.IntegerField(default=0)),
                ('childhood_section', models.TextField(blank=True, null=True)),
                ('career_section', models.TextField(blank=True, null=True)),
                ('relationships_section', models.TextField(blank=True, null=True)),
                ('wisdom_section', models.TextField(blank=True, null=True)),
                ('challenges_section', models.TextField(blank=True, null=True)),
                ('personality_section', models.TextField(blank=True, null=True)),
                ('transcription_service', models.CharField(default='openai_whisper', max_length=50)),
                ('model_used', models.CharField(default='whisper-1', max_length=50)),
                ('confidence_score', models.FloatField(blank=True, help_text='0.00 to 1.00', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='users.user')),
            ],
            options={
                'db_table': 'transcripts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AudioRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_path', models.CharField(max_length=500, unique=True)),
                ('public_url', models.URLField(max_length=1000)),
                ('file_size_bytes', models.BigIntegerField()),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('format', models.CharField(choices=[('webm', 'WebM'), ('mp3', 'MP3'), ('wav', 'WAV')], max_length=10)),
                ('question_number', models.IntegerField()),
                ('domain', models.CharField(choices=[('childhood', 'Childhood'), ('career', 'Career'), ('family', 'Family'), ('wisdom', 'Wisdom'), ('challenges', 'Challenges'), ('personality', 'Personality')], max_length=20)),
                ('question_text', models.TextField()),
                ('quality_score', models.FloatField(blank=True, help_text='0.00 to 1.00', null=True)),
                ('background_noise', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True)),
                ('upload_status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('transcribed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='users.user')),
            ],
            options={
                'db_table': 'audio_recordings',
                'ordering': ['question_number'],
                'indexes': [models.Index(fields=['user', 'question_number'], name='audio_recor_user_id_9d2853_idx'), models.Index(fields=['user'], name='audio_recor_user_id_5a59b5_idx'), models.Index(fields=['transcribed'], name='audio_recor_transcr_8864f0_idx'), models.Index(fields=['domain'], name='audio_recor_domain_1553c4_idx')],
                'unique_together': {('user', 'question_number')},
            },
        ),
    ]
