# Generated by Django 5.0 on 2026-01-12 15:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField(help_text='The question to ask the user')),
                ('domain', models.CharField(choices=[('childhood', 'Childhood'), ('family', 'Family'), ('career', 'Career'), ('wisdom', 'Wisdom'), ('challenges', 'Challenges'), ('personality', 'Personality')], max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Display order (1-30)')),
                ('is_active', models.BooleanField(default=True, help_text='Is this question active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tip', models.TextField(blank=True, help_text='Helpful tip for answering this question', null=True)),
                ('suggested_duration_seconds', models.IntegerField(default=60, help_text='Suggested answer duration in seconds')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['domain', 'order'], name='recordings__domain_997479_idx'), models.Index(fields=['is_active'], name='recordings__is_acti_8272b5_idx')],
                'unique_together': {('domain', 'order')},
            },
        ),
    ]
