# Generated by Django 5.0 on 2026-01-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0002_recordingquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiorecording',
            name='domain',
            field=models.CharField(choices=[('childhood', 'Childhood'), ('career', 'Career'), ('family', 'Family'), ('wisdom', 'Wisdom'), ('challenges', 'Challenges'), ('personality', 'Personality'), ('combined', 'Combined')], max_length=20),
        ),
    ]
