# Generated by Django 5.0 on 2026-02-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='package_tier',
            field=models.CharField(choices=[('premium', 'VoiceVault')], max_length=20),
        ),
    ]
