# Generated by Django 5.0 on 2026-01-11 15:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('package_tier', models.CharField(choices=[('lite', 'Lite'), ('premium', 'Premium'), ('family', 'Family')], default='lite', max_length=20)),
                ('recording_completed', models.BooleanField(default=False)),
                ('recording_started_at', models.DateTimeField(blank=True, null=True)),
                ('ai_ready', models.BooleanField(db_index=True, default=False)),
                ('ai_processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('ai_processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('stripe_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_completed', models.BooleanField(default=False)),
                ('payment_amount', models.IntegerField(default=0, help_text='Amount in cents')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='users_email_4b85f2_idx'), models.Index(fields=['stripe_customer_id'], name='users_stripe__0fdd23_idx'), models.Index(fields=['ai_ready'], name='users_ai_read_97d2b3_idx'), models.Index(fields=['created_at'], name='users_created_6541e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse'), ('child', 'Child'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('friend', 'Friend')], max_length=20)),
                ('has_access', models.BooleanField(default=False)),
                ('invitation_sent_at', models.DateTimeField(auto_now_add=True)),
                ('invitation_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('conversation_count', models.IntegerField(default=0)),
                ('last_conversation_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='users.user')),
                ('user_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_access', to='users.user')),
            ],
            options={
                'db_table': 'family_members',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ai_owner', 'email'], name='family_memb_ai_owne_d202b8_idx'), models.Index(fields=['has_access'], name='family_memb_has_acc_d54a44_idx')],
                'unique_together': {('ai_owner', 'email')},
            },
        ),
    ]
