# Generated by Django 5.0 on 2026-01-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_hash',
            field=models.CharField(blank=True, help_text='Hashed password', max_length=255, null=True),
        ),
    ]
