# Generated by Django 5.0 on 2026-02-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='package_tier',
            field=models.CharField(choices=[('premium', 'VoiceVault')], default='premium', max_length=20),
        ),
    ]
