# Generated by Django 5.0 on 2026-06-04 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_freemium_entitlements'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_user_id_73c422_idx',
            old_name='audit_logs_user_id_826ad1_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_action_31f574_idx',
            old_name='audit_logs_action_52d1a7_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_target__9fc8de_idx',
            old_name='audit_logs_target__2e9492_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_created_262184_idx',
            old_name='audit_logs_created_a8d632_idx',
        ),
        migrations.RenameIndex(
            model_name='consentrecord',
            new_name='consent_rec_user_id_5843c5_idx',
            old_name='consent_rec_user_id_0ff159_idx',
        ),
        migrations.RenameIndex(
            model_name='consentrecord',
            new_name='consent_rec_accepte_708460_idx',
            old_name='consent_rec_accepte_f7c8a9_idx',
        ),
        migrations.RenameIndex(
            model_name='usagequota',
            new_name='usage_quota_quota_r_5a0e6b_idx',
            old_name='usage_quota_quota_r_05811b_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_plan_ty_daaa64_idx',
            old_name='users_plan_ty_88af38_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_is_prem_41b83a_idx',
            old_name='users_is_prem_1c1c6c_idx',
        ),
    ]
