# Generated by Django 5.0 on 2026-06-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_audit_logs_user_id_826ad1_idx_audit_logs_user_id_73c422_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
