# Generated by Django 5.0 on 2026-01-11 15:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voice_clone_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('voice_quality_score', models.FloatField(blank=True, help_text='0.00 to 1.00', null=True)),
                ('voice_similarity_target', models.FloatField(default=0.85)),
                ('system_prompt', models.TextField(help_text='Complete system prompt for GPT-4')),
                ('ai_model', models.CharField(default='gpt-4', max_length=50)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=500)),
                ('personality_data', models.JSONField(default=dict, help_text='Structured personality analysis')),
                ('quality_approved', models.BooleanField(default=False)),
                ('admin_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to='users.user')),
            ],
            options={
                'db_table': 'ai_configurations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['voice_clone_id'], name='ai_configur_voice_c_0f6123_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIUsageTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_provider', models.CharField(choices=[('openai', 'OpenAI'), ('elevenlabs', 'ElevenLabs')], max_length=20)),
                ('operation', models.CharField(choices=[('transcribe', 'Transcribe'), ('chat', 'Chat'), ('voice_generation', 'Voice Generation'), ('personality_analysis', 'Personality Analysis')], max_length=30)),
                ('tokens_used', models.IntegerField(blank=True, help_text='For OpenAI', null=True)),
                ('characters_used', models.IntegerField(blank=True, help_text='For ElevenLabs', null=True)),
                ('cost_usd', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
            options={
                'db_table': 'api_usage_tracking',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='api_usage_t_user_id_94256a_idx'), models.Index(fields=['api_provider'], name='api_usage_t_api_pro_e658cf_idx'), models.Index(fields=['created_at'], name='api_usage_t_created_66beed_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcessingQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('transcribe', 'Transcribe'), ('analyze_personality', 'Analyze Personality'), ('clone_voice', 'Clone Voice'), ('test_ai', 'Test AI')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('priority', models.IntegerField(default=5, help_text='1-10, higher is more important')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('task_data', models.JSONField(default=dict, help_text='Task-specific parameters')),
                ('result_data', models.JSONField(blank=True, help_text='Task results', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'processing_queue',
                'ordering': ['-priority', 'created_at'],
                'indexes': [models.Index(fields=['status', 'priority'], name='processing__status_d27a87_idx'), models.Index(fields=['user'], name='processing__user_id_a8a123_idx')],
            },
        ),
    ]
