# Generated by Django 5.0 on 2026-01-11 15:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('response_text', models.TextField()),
                ('audio_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('response_time_ms', models.IntegerField(help_text='Total response generation time')),
                ('gpt_tokens_used', models.IntegerField(blank=True, null=True)),
                ('elevenlabs_characters_used', models.IntegerField(blank=True, null=True)),
                ('user_rating', models.IntegerField(blank=True, help_text='1-5 star rating', null=True)),
                ('user_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ai_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='users.user')),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.familymember')),
            ],
            options={
                'db_table': 'conversations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ai_owner', 'created_at'], name='conversatio_ai_owne_0b6363_idx'), models.Index(fields=['family_member'], name='conversatio_family__c0c4e4_idx'), models.Index(fields=['created_at'], name='conversatio_created_694913_idx')],
            },
        ),
    ]
